bcgov/BCP-CMS

- src/backend/.gitignore
- src/backend/api/public-advisory-event/models/public-advisory-event.settings.json
- src/backend/api/public-advisory/models/public-advisory.settings.json
- src/backend/config/functions/bootstrap.js
model changes on public_advisory and public_advisory_event
rename function names on bootstrap
> public advisory model change

- src/frontend/src/components/page/advisoryDashboard/AdvisoryDashboard.js
add search on the advisory dashboard
> advisory dashboard search

- src/backend/config/functions/bootstrap.js
- src/backend/data/public-advisory-event.json
Hi Siva, sorry I more PR today, just loading some data. Thanks
> load public advisory test data

- src/backend/api/event-type/models/event-type.settings.json
- src/backend/api/public-advisory-event/models/public-advisory-event.settings.json
I added the protected area field on the public-advisory-event model
> add protected area field to public advisory event

- src/backend/api/access-status/documentation/1.0.0/access-status.json
- src/backend/api/event-type/documentation/1.0.0/event-type.json
- src/backend/api/link/config/routes.json
- src/backend/api/link/controllers/link.js
- src/backend/api/link/models/link.js
- src/backend/api/link/models/link.settings.json
- src/backend/api/link/services/link.js
- src/backend/api/public-advisory-event/documentation/1.0.0/public-advisory-event.json
- src/backend/api/public-advisory-event/models/public-advisory-event.settings.json
- src/backend/api/public-advisory/documentation/1.0.0/public-advisory.json
- src/backend/api/public-advisory/models/public-advisory.settings.json
- src/backend/api/urgency/config/routes.json
- src/backend/api/urgency/controllers/urgency.js
- src/backend/api/urgency/models/urgency.js
- src/backend/api/urgency/models/urgency.settings.json
- src/backend/api/urgency/services/urgency.js
- src/backend/config/functions/bootstrap.js
- src/backend/data/access-status.json
- src/backend/data/public-advisory-event.json
- src/backend/data/urgency.json
> Ab model changes

- src/frontend/src/components/page.css
- src/frontend/src/components/page/advisoryDashboard/AdvisoryDashboard.js
- src/frontend/src/components/page/createAdvisory/CreateAdvisory.css
- src/frontend/src/components/page/createAdvisory/CreateAdvisory.js
- src/frontend/src/components/page/home/Home.css
- src/frontend/src/components/page/home/Home.js
> Added login page

- src/frontend/src/components/page/advisoryDashboard/AdvisoryDashboard.css
- src/frontend/src/components/page/advisoryDashboard/AdvisoryDashboard.js
- Public Advisory Layout changes
> advisory dashboard layout changes

- src/frontend/src/components/page.css
- src/frontend/src/components/page/advisoryDashboard/AdvisoryDashboard.css
- src/frontend/src/components/page/createAdvisory/CreateAdvisory.css
- src/frontend/src/components/page/createAdvisory/CreateAdvisory.js
> Added ability to add multiple parks in advisory

- src/backend/api/public-advisory/documentation/1.0.0/public-advisory.json
- src/backend/api/public-advisory/models/public-advisory.settings.json
- src/backend/extensions/documentation/documentation/1.0.0/full_documentation.json
- Public Advisory Model Change with the new fields below:
- Regions[]
- Sections[]
- ManagementAreas[]
> model change - public advisory

- src/api/BCParksApi/Controllers/ApiController.cs
- src/api/BCParksApi/appsettings.Development.json
- src/api/BCParksApi/appsettings.json
- src/backend/.env.example
- src/backend/api/token/config/routes.json
- src/backend/api/token/controllers/token.js
- src/backend/api/token/models/token.js
- src/backend/api/token/models/token.settings.json
- src/backend/api/token/services/token.js
- src/backend/config/functions/bootstrap.js
- src/backend/extensions/documentation/documentation/1.0.0/full_documentation.json
- src/backend/extensions/users-permissions/config/policies/permissions.js
- src/backend/extensions/users-permissions/models/User.settings.json
- src/frontend/src/components/page/createAdvisory/CreateAdvisory.css
> Added authenticated user token for strapi

- .gitignore
- src/api/BCParksApi/Controllers/ApiController.cs
- src/frontend/src/components/page/advisoryDashboard/AdvisoryDashboard.js
- src/frontend/src/components/page/createAdvisory/CreateAdvisory.js
- src/frontend/src/components/page/updateAdvisory/UpdateAdvisory.js
- src/frontend/src/routes/AppRouter.js
- Consistent page loader and PUT api method
> Consistent page loader and PUT api method

- src/frontend/src/components/composite/accountInfo/AccountInfo.js
- Display name in account info
> Display name in account info

- src/frontend/src/components/page/advisoryDashboard/AdvisoryDashboard.css
- src/frontend/src/components/page/advisoryDashboard/AdvisoryDashboard.js
- src/frontend/src/components/page/updateAdvisory/UpdateAdvisory.js
- Layout changes and some fixes on the advisory dashboard and approval
> Ab advisory update v2

- src/frontend/src/components/composite/accountInfo/AccountInfo.js
- src/frontend/src/components/page/home/Home.js
> Removed hardcoded data

- src/frontend/src/components/page/advisoryDashboard/AdvisoryDashboard.js
- Fix public advisory dashboard hanging issue
> fix hanging issue

- src/frontend/src/components/page/advisoryDashboard/AdvisoryDashboard.js
- add park name in advisory dashboard
> add park name in advisory dashboard

- src/backend/config/functions/bootstrap.js
- src/frontend/src/components/page/advisoryDashboard/AdvisoryDashboard.js
- src/frontend/src/components/page/updateAdvisory/UpdateAdvisory.js
- delete and reload public advisory 
- add parks on the the dashboard
- add timer icon on expired date
> Ab data update

- src/frontend/src/axios_config.js
- src/frontend/src/components/page/createAdvisory/CreateAdvisory.js
- src/frontend/src/components/page/updateAdvisory/UpdateAdvisory.js
> Temp change to be reverted

- src/frontend/src/axios_config.js
- src/frontend/src/components/page/createAdvisory/CreateAdvisory.js
- src/frontend/src/components/page/updateAdvisory/UpdateAdvisory.js
This reverts commit 7cf2c08ec06eae20f03166093c9247685af8504b.
> Revert "Temp change to be reverted"

- src/backend/api/advisory-status/documentation/1.0.0/advisory-status.json
- src/backend/api/advisory-status/models/advisory-status.settings.json
- src/backend/api/data-load-setting/config/routes.json
- src/backend/api/data-load-setting/controllers/data-load-setting.js
- src/backend/api/data-load-setting/models/data-load-setting.js
- src/backend/api/data-load-setting/models/data-load-setting.settings.json
- src/backend/api/data-load-setting/services/data-load-setting.js
- src/backend/api/public-advisory/documentation/1.0.0/public-advisory.json
- src/backend/api/urgency/documentation/1.0.0/urgency.json
- src/backend/config/functions/bootstrap.js
- src/backend/data/advisory-status.json
- src/backend/data/urgency.json
- src/backend/extensions/documentation/documentation/1.0.0/full_documentation.json
- model changes 
- add order sequence  and code on urgency model
- add code on advisory-status model
- add a reload and purge  option on bootstrap data load
> Ab model changes v2

- src/backend/config/functions/bootstrap.js
- src/backend/data/advisory-status.json
- src/backend/extensions/documentation/documentation/1.0.0/full_documentation.json
- src/frontend/src/components/page/advisoryDashboard/AdvisoryDashboard.css
- src/frontend/src/components/page/advisoryDashboard/AdvisoryDashboard.js
- advisory dashboard status icons
- bootstrap changes to reload advisory statuses and urgencies
> Ab public advisory v7

- src/api/BCParksApi/Controllers/ApiController.cs
- src/backend/config/functions/bootstrap.js
- src/backend/extensions/documentation/documentation/1.0.0/full_documentation.json
- src/frontend/.env.example
- src/frontend/src/axios_config.js
- src/frontend/src/components/page/createAdvisory/CreateAdvisory.js
- src/frontend/src/components/page/error/Error.js
> After hour and Stat holiday calculation

- src/frontend/src/components/page.css
- src/frontend/src/components/page/createAdvisory/CreateAdvisory.css
- src/frontend/src/components/page/createAdvisory/CreateAdvisory.js
- src/frontend/src/components/page/updateAdvisory/UpdateAdvisory.css
- src/frontend/src/index.css
> Submit, publish and save draft for advisory

- src/backend/api/public-advisory/documentation/1.0.0/public-advisory.json
- src/backend/api/public-advisory/models/public-advisory.settings.json
- src/backend/extensions/documentation/documentation/1.0.0/full_documentation.json
- src/frontend/src/components/composite/accountInfo/AccountInfo.js
- src/frontend/src/components/page/createAdvisory/CreateAdvisory.css
- src/frontend/src/components/page/createAdvisory/CreateAdvisory.js
> Added new data fields in advisory form

- src/frontend/src/components/page/createAdvisory/CreateAdvisory.css
- src/frontend/src/components/page/createAdvisory/CreateAdvisory.js
> Added confirmation popup to create advisory

- src/backend/config/functions/cron.js
- src/backend/config/server_template.js
- src/frontend/src/components/page/createAdvisory/CreateAdvisory.js
> Added publish/unpublish advisory scheduler

- src/backend/config/functions/bootstrap.js
- src/backend/config/functions/cron.js
- src/frontend/package.json
- src/frontend/src/components/page/createAdvisory/CreateAdvisory.js
- Timezone and status code fixes
> Timezone and status code fixes

- src/cms/api/management-area/documentation/1.0.0/management-area.json
- src/cms/api/protected-area/documentation/1.0.0/protected-area.json
- src/cms/api/protected-area/models/protected-area.settings.json
- src/cms/api/public-advisory/documentation/1.0.0/public-advisory.json
- src/cms/api/site/documentation/1.0.0/site.json
- src/cms/config/functions/bootstrap.js
- src/cms/extensions/documentation/documentation/1.0.0/full_documentation.json
- BC-135: Add FeatureId to ProctectedArea
> add featureId on Par (for BCGNIS)

- src/cms/api/fire-ban-prohibition/config/routes.json
- src/cms/api/fire-ban-prohibition/controllers/fire-ban-prohibition.js
- src/cms/api/fire-ban-prohibition/models/fire-ban-prohibition.js
- src/cms/api/fire-ban-prohibition/models/fire-ban-prohibition.settings.json
- src/cms/api/fire-ban-prohibition/services/fire-ban-prohibition.js
- src/cms/api/fire-centre/models/fire-centre.settings.json
- src/cms/data/functions/initialDataLoad.js
- src/cms/data/functions/loadOtherData.js
- src/cms/extensions/documentation/documentation/1.0.0/full_documentation.json
- BC-73 Campfire bans
- BC-121 BC Wildfire Service for current campfire ban status
> load wildfire bans and prohibitions dataset

- src/admin/package.json
> Added missing dependency

- src/admin/src/components/composite/advisoryForm/AdvisoryForm.css
- src/admin/src/components/composite/advisoryForm/AdvisoryForm.js
- src/admin/src/components/page.css
- src/admin/src/components/page/advisory/Advisory.js
- src/admin/src/validators/AdvisoryValidator.js
> Added form validation

- src/admin/src/components/page/advisoryDashboard/AdvisoryDashboard.js
> Updated advisory query

- src/cms/api/protected-area/config/routes.json
- src/cms/api/protected-area/controllers/protected-area.js
- src/cms/api/protected-area/documentation/1.0.0/protected-area.json
- src/cms/data/access-status.json
- src/cms/data/functions/initialDataLoad.js
- src/cms/extensions/documentation/documentation/1.0.0/full_documentation.json
- BC-71 a view of the parks based on parks advisory
> park status api

- src/admin/src/components/composite/advisoryForm/AdvisoryForm.css
- src/admin/src/components/composite/advisoryForm/AdvisoryForm.js
- src/admin/src/components/page/advisory/Advisory.js
- src/admin/src/utils/AdvisoryUtils.js
- src/admin/src/validators/AdvisoryValidator.js
- src/cms/api/management-area/documentation/1.0.0/management-area.json
- src/cms/api/management-area/models/management-area.settings.json
- src/cms/api/public-advisory/documentation/1.0.0/public-advisory.json
- src/cms/api/region/documentation/1.0.0/region.json
- src/cms/api/region/models/region.settings.json
- src/cms/api/section/documentation/1.0.0/section.json
- src/cms/api/section/models/section.settings.json
- src/cms/extensions/documentation/documentation/1.0.0/full_documentation.json
- Added auto addition of parks from area
> Added auto addition of parks from area

- src/admin/src/components/page/home/Home.js
> Home page updates

- src/admin/package.json
- src/admin/src/App.js
- src/admin/src/components/page/advisoryDashboard/AdvisoryDashboard.js
- src/cms/api/protected-area/config/routes.json
- src/cms/api/protected-area/controllers/protected-area.js
- src/cms/api/protected-area/documentation/1.0.0/protected-area.json
- src/cms/data/functions/initialDataLoad.js
- src/cms/extensions/documentation/documentation/1.0.0/full_documentation.json
- performance improvements and minor layout changes on advisory dashboard
- add new route (/protectedAreas/names)  for getting park names only  - to improve load times
- remove temp data load scripts
> performance improvements and minor layout changes

- src/admin/src/components/composite/advisoryForm/AdvisoryForm.js
- src/admin/src/components/page/advisory/Advisory.js
- src/admin/src/utils/AdvisoryUtils.js
- src/admin/src/validators/AdvisoryValidator.js
> Performance updates

- src/cms/data/functions/reloadData.js
> Fixed file name error

- src/admin/src/components/composite/advisoryForm/AdvisoryForm.js
- src/admin/src/components/page.css
- src/admin/src/components/page/advisory/Advisory.js
- src/admin/src/components/page/advisoryDashboard/AdvisoryDashboard.js
- src/admin/src/components/page/advisorySummary/AdvisorySummary.css
- src/admin/src/components/page/advisorySummary/AdvisorySummary.js
- src/admin/src/components/page/advisorySummary/AdvisorySummary.stories.js
- src/admin/src/components/page/advisorySummary/AdvisorySummary.test.js
- src/admin/src/routes/AppRouter.js
- src/cms/extensions/documentation/documentation/1.0.0/full_documentation.json
> Added advisory summary page

- src/admin/src/components/page/advisorySummary/AdvisorySummary.js
> Updated Clipboard funtionality and url

- src/cms/api/management-area/documentation/1.0.0/management-area.json
- src/cms/api/park-activity/models/park-activity.settings.json
- src/cms/api/park-facility/models/park-facility.js
- src/cms/api/park-facility/models/park-facility.settings.json
- src/cms/api/protected-area/documentation/1.0.0/protected-area.json
- src/cms/api/protected-area/models/protected-area.settings.json
- src/cms/api/public-advisory/documentation/1.0.0/public-advisory.json
- src/cms/api/site/documentation/1.0.0/site.json
- src/cms/api/site/models/site.settings.json
- src/cms/data/functions/initialDataLoad.js
- src/cms/data/functions/loadOtherData.js
- src/cms/extensions/documentation/documentation/1.0.0/full_documentation.json
- Park Activity & Facility data load
- Model changes Park Activity & Facility 
> park activity & facility data load
